### ISSUE TITLE
当list数据只有一个的时候，滑动view会报java.lang.StackOverflowError

### ISSUE THREAD

**Issue by LitbLeo** [czy1121/bannerview#3]
`FATAL EXCEPTION: main
                                                                       Process: com.xingjia.secarmobi, PID: 26931
                                                                       java.lang.StackOverflowError
                                                                           at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:634)
                                                                           at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:630)
                                                                           at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:622)
                                                                           at ezy.ui.view.LoopViewPager.setCurrentItem(LoopViewPager.java:71)
                                                                           at ezy.ui.view.LoopViewPager$1.onPageScrolled(LoopViewPager.java:171)
                                                                           at android.support.v4.view.ViewPager.dispatchOnPageScrolled(ViewPager.java:1950)
                                                                           at android.support.v4.view.ViewPager.onPageScrolled(ViewPager.java:1924)
                                                                           at android.support.v4.view.ViewPager.pageScrolled(ViewPager.java:1862)
                                                                           at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:693)
                                                                           at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:669)
                                                                           at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:630)
                                                                           at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:622)
                                                                           at ezy.ui.view.LoopViewPager.setCurrentItem(LoopViewPager.java:71)
                                                                           at ezy.ui.view.LoopViewPager$1.onPageScrolled(LoopViewPager.java:171)
                                                                           at android.support.v4.view.ViewPager.dispatchOnPageScrolled(ViewPager.java:1950)
                                                                           at android.support.v4.view.ViewPager.onPageScrolled(ViewPager.java:1924)
                                                                           at android.support.v4.view.ViewPager.pageScrolled(ViewPager.java:1862)
                                                                           at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:693)
                                                                           at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:669)
                                                                           at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:630)
                                                                           at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:622)
                                                                           at ezy.ui.view.LoopViewPager.setCurrentItem(LoopViewPager.java:71)
                                                                           at ezy.ui.view.LoopViewPager$1.onPageScrolled(LoopViewPager.java:171)
                                                                           at android.support.v4.view.ViewPager.dispatchOnPageScrolled(ViewPager.java:1950)
                                                                           at android.support.v4.view.ViewPager.onPageScrolled(ViewPager.java:1924)
                                                                           at android.support.v4.view.ViewPager.pageScrolled(ViewPager.java:1862)
                                                                           at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:693)
                                                                           at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:669)
                                                                           at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:630)
                                                                           at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:622)
                                                                           at ezy.ui.view.LoopViewPager.setCurrentItem(LoopViewPager.java:71)
                                                                           at ezy.ui.view.LoopViewPager$1.onPageScrolled(LoopViewPager.java:171)
                                                                           at android.support.v4.view.ViewPager.dispatchOnPageScrolled(ViewPager.java:1950)
                                                                           at android.support.v4.view.ViewPager.onPageScrolled(ViewPager.java:1924)
                                                                           at android.support.v4.view.ViewPager.pageScrolled(ViewPager.java:1862)
                                                                           at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:693)
                                                                           at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:669)
                                                                           at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:630)
                                                                           at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:622)
                                                                           at ezy.ui.view.LoopViewPager.setCurrentItem(LoopViewPager.java:71)
                                                                           at ezy.ui.view.LoopViewPager$1.onPageScrolled(LoopViewPager.java:171)
                                                                           at android.support.v4.view.ViewPager.dispatchOnPageScrolled(ViewPager.java:1950)
                                                                           at android.support.v4.view.ViewPager.onPageScrolled(ViewPager.java:1924)
                                                                           at android.support.v4.view.ViewPager.pageScrolled(ViewPager.java:1862)
                                                                           at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:693)
                                                                           at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:669)
                                                                           at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:630)
                                                                           at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:622)
                                                                           at ezy.ui.view.LoopViewPager.setCurrentItem(LoopViewPager.java:71)
                                                                           at ezy.ui.view.LoopViewPager$1.onPageScrolled(LoopViewPager.java:171)
                                                                           at android.support.v4.view.ViewPager.dispatchOnPageScrolled(ViewPager.java:1950)
                                                                           at android.support.v4.view.ViewPager.onPageScrolled(ViewPager.java:1924)
                                                                       	at android.support.v4.view.ViewPager.pageScrolled(ViewPager.java:1862`

**Comment by hero0812** [comment]
how to resolve?

**Comment by czy1121** [comment]
已修复 1.0.2
